id = "enma-lsp"
name = "Enma LSP"
version = "0.0.1"
schema_version = 1
authors = ["Shadowthijs <logtenbergthijs@yahoo.com>"]
description = "Enma language extension"
repository = "https://github.com/shadowthijs/enma-lsp-zed"

[grammars.enma]
repository = "https://github.com/shadowthijs/enma-lsp-zed"
path = "tree-sitter-enma"
rev = "f0a2a9d91980beb8af7f937d927e97fe3425ca94"

[language_servers.enma-lsp]
name = "Enma LSP"
languages = ["Enma"]
