id = "enma-lsp"
name = "Enma LSP"
version = "0.0.1"
schema_version = 1
authors = ["Shadowthijs <logtenbergthijs@yahoo.com>"]
description = "Enma language extension"
repository = "https://github.com/shadowthijs/enma-lsp-zed"

[grammars.enma]
repository = "https://github.com/shadowthijs/enma-lsp-zed"
path = "tree-sitter-enma"
rev = "4f261b40ad1bac023ec5f51877227634ab17c01a"
