id = "enma-lsp"
name = "Enma LSP"
version = "0.0.1"
schema_version = 1
authors = ["Shadowthijs <logtenbergthijs@yahoo.com>"]
description = "Enma language extension"
repository = "https://github.com/shadowthijs/enma-lsp-zed"

[grammars.enma]
repository = "https://github.com/shadowthijs/enma-lsp-zed"
path = "tree-sitter-enma"
rev = "a8eba7275a96afdbf9d4696efb4f11661a051cba"

[language_servers.enma-lsp]
name = "Enma LSP"
languages = ["Enma"]
